ENG-4956 test

diff --git a/bin/mod/ent-check-env b/bin/mod/ent-check-env
--- a/bin/mod/ent-check-env
+++ b/bin/mod/ent-check-env
@@ -24,7 +24,7 @@ RUN() {
 
   export WAS_DEVELOP_CHECKED=true   # in order to allow to run the version command
 
-  
+
   # DEVELOP TOOLS
   $M_DEVL && check-env.develop.minimal-tools-requirements
 
@@ -40,7 +40,7 @@ RUN() {
   $M_KUBE && check-env.runtime.minimal-sys-requirements
   $M_KUBE && $M_QS && check-env.runtime.quickstart.apply-fixes
   $M_KUBE && check-env.runtime.check-dns
-  
+
   # EXTENSION MODULES
   check-env.extention-modules "$ENTANDO_CLI_CHECKENV_MODE"
 
@@ -65,7 +65,7 @@ check-env.common.minimal-requirements() {
   }
   check_ver "grep" "*.*.*" "--version | head -n 1" || DEPENDENCY_ERROR "$FAIL_MSG"
   check_ver "cat" "-" "-" || DEPENDENCY_ERROR "$FAIL_MSG"
-  
+
   check_ver "_jq" "*.*.*" "--version" || {
     if ask "Should I try to install it?" "y"; then
       (_pkg_get "jq") || DEPENDENCY_ERROR "$FAIL_MSG"
@@ -74,7 +74,7 @@ check-env.common.minimal-requirements() {
     fi
   }
 }
-  
+
 check-env.runtime.minimal-sys-requirements() {
   check_ver "hostname" "*.*.*" "--version | head -n 1" || DEPENDENCY_ERROR "$FAIL_MSG";
   check_ver "dig" "*.*.*" "-v 2>&1" literal || DEPENDENCY_ERROR "$FAIL_MSG";
@@ -86,7 +86,7 @@ check-env.runtime.check-k3s() {
     VER_K3S_REQ="$ENTANDO_K3S_VERSION_OVERRIDE"
     VER_K3S_DEF="$ENTANDO_K3S_VERSION_OVERRIDE"
   fi
-  
+
   if check_ver "k3s" "$VER_K3S_REQ" "--version 2>/dev/null | _perl_sed 's/k3s version (.*)\+k.*/\1/'"; then
     # shellcheck disable=SC2154
     _log_i "\tfound: $check_ver_res => OK"
@@ -97,7 +97,7 @@ check-env.runtime.check-k3s() {
       prompt "Recommended dependency not found, some command may not work as expected.\nPress enter to continue.."
     fi
   fi
-}  
+}
 
 check-env.extention-modules() {
   local module;
@@ -113,13 +113,13 @@ check-env.develop.minimal-tools-requirements() {
   check_ver "java" "*.*.*" "-version 2>&1 | head -n 1 | awk '{gsub(/\"/, \"\", \$3);print \$3}'" || {
     DEPENDENCY_ERROR "$FAIL_MSG"
   }
-  
+
   check_ver "docker" "*.*.*" "--version | sed 's/.*version \([0-9a-zA-Z.+-]*\).*/\1/'" || DEPENDENCY_ERROR "$FAIL_MSG"
 
   check_ver "watch" "*.*.*" "-v" || {
     prompt "Recommended dependency not found, workaround will be applied.\nPress enter to continue.."
   }
-  
+
   check_ver "_crane" "*.*.*" "version" || {
     if ask "Should I try to install it?" "y"; then
       (_pkg_get "crane") || DEPENDENCY_ERROR "$FAIL_MSG"
@@ -178,17 +178,22 @@ check-env.check-node() {
   mkdir -p "lib/node"
 
   _log_i "Checking ENT private installation of node.js.."
-  
+
   if [ -n "$ENTANDO_NODE_VERSION_OVERRIDE" ]; then
+    echo "######### OVERRIDING NODE WITH ${ENTANDO_NODE_VERSION_OVERRIDE}"
     VER_NODE_REQ="$ENTANDO_NODE_VERSION_OVERRIDE"
     VER_NODE_DEF="$ENTANDO_NODE_VERSION_OVERRIDE"
   fi
-  
+
+  echo "######### VER_NODE_REQ ${VER_NODE_REQ}"
+  echo "######### VER_NODE_DEF ${VER_NODE_DEF}"
+
   check_ver "_ent-node" "$VER_NODE_REQ" "--version" "quiet,verbose" "" || {
     _log_w "ENT private node.js installation is not available"
     if ask "Should I try to install it?" "y"; then
+      echo "######### INSTALLING ${VER_NODE_DEF}"
       node.install-node "$VER_NODE_DEF"
-      
+
       _log_i "Node installed and activated:"
       echo "  NODE: $(_ent-node --version)"
       echo "  NPM: $(_ent-npm_direct --version)"
@@ -196,7 +201,7 @@ check-env.check-node() {
       DEPENDENCY_ERROR "Mandatory dependency not available"
     fi
   }
-  
+
   reload_cfg "$ENTANDO_GLOBAL_CFG"
   reload_cfg
   node.activate_environment || DEPENDENCY_ERROR "Unable to activate the found version"
@@ -250,7 +255,7 @@ check-env.check-bundler() {
   local FLAGS FORCE=false
   parse-version-flags FLAGS VER_ENTANDO_BUNDLER_DEF VER_ENTANDO_BUNDLER_REQ ENTANDO_BUNDLER_VERSION_OVERRIDE
   _str_contains "$FLAGS" ",f," && FORCE=true
-  
+
   check_npm_git_package "$REPO_ENTANDO_BUNDLER_ADDR" \
     "$VER_ENTANDO_BUNDLER_REQ" "$VER_ENTANDO_BUNDLER_DEF" \
     "$C_ENTANDO_BUNDLER_DIR" "$C_ENTANDO_BUNDLER_DIR" \
@@ -262,13 +267,13 @@ check-env.check-bundler() {
 parse-version-flags() {
   local _tmp_ver="${!2}" _tmp_flags
   [ -n "${!4}" ] && _tmp_ver="${!4}"
-  
+
   IFS=: read -r _tmp_flags _tmp_ver <<< "$_tmp_ver"
   [ -z "$_tmp_ver" ] && {
     _tmp_ver="$_tmp_flags"
     _tmp_flags=""
   }
-  
+
   _set_var "$1" ",$_tmp_flags,"
   _set_var "$2" "$_tmp_ver"
   if [ -n "${!4}" ]; then
@@ -304,8 +309,8 @@ check_ver_cfg() {
 # $4: package name
 # $5: package description
 check_npm_git_package() {
-  local FULL=false; [ "$1" = "--full" ] && { FULL=true; shift; } 
-  local WITHINST=true; [ "$1" = "--no-local-install" ] && { WITHINST=false; shift; } 
+  local FULL=false; [ "$1" = "--full" ] && { FULL=true; shift; }
+  local WITHINST=true; [ "$1" = "--no-local-install" ] && { WITHINST=false; shift; }
   local ADDR="$1"; shift
   local VER_REQ="$1"; shift
   local VER_DEF="$1"; shift
@@ -320,10 +325,10 @@ check_npm_git_package() {
       VER_REQ="$VER_OVERRIDE"
       VER_DEF="$VER_OVERRIDE"
     fi
-    
+
     [ ! -d "$ENT_OPTS_ENTANDO" ] && __mk_disdir "$ENT_OPTS_ENTANDO"
     __cd "$ENT_OPTS_ENTANDO"
-    
+
     local skip=false forced=false
     if [ -f "$PACKAGE_NAME/$VER_REQ/.entando-finalized" ]; then
       if [ "$FORCE" == "true" ]; then
@@ -335,7 +340,7 @@ check_npm_git_package() {
         skip=true
       fi
     fi
-    
+
     if "$skip"; then
       _log_i "\tfound: $VER_REQ => OK"
       _log_i "\tupdating bins"
@@ -359,15 +364,15 @@ check_npm_git_package() {
           if [[ -d "$BASE_PACKAGE_DIR/$VER_DEF" ]]; then
             __mk_disdir --mark "$BASE_PACKAGE_DIR/$VER_DEF"
           fi
-          
+
           if [ "$EC" != 0 ]; then
             [[ -d "$BASE_PACKAGE_DIR/$VER_DEF" ]] && __rm_disdir "$BASE_PACKAGE_DIR/$VER_DEF"
             _FATAL -s "Error while cloning the repository of package \"$PACKAGE_DESC\""
           fi
-          
+
           [[ "$PWD" != "$BASE_PACKAGE_DIR/$VER_DEF" ]] && _FATAL -s "Inconsistent directory structure"
 
-          # CLEANUP          
+          # CLEANUP
           (
             __cd "$ENT_NODE_MODS"
             _remove_broken_symlink "$PACKAGE_NAME"
@@ -375,10 +380,10 @@ check_npm_git_package() {
             _remove_broken_symlink "$PACKAGE_NAME"
             _ent-npm_direct uninstall --global "$PACKAGE_NAME" &> /dev/null
           ) &>/dev/null
-          
+
           # BUILD
           _log_i "Building.."
-          
+
           (
             if $FULL; then
               ___npm "PHASE 1/a" install
@@ -418,7 +423,7 @@ check-env.npm-registry-package() {
   local FORCE="$1"; shift; [ "$FORCE" != "true" ] && { FORCE=""; }
 
   _log_i "Checking ENT private installation of $package.."
-  
+
   check_ver "_ent-$package" "$version_req" "--ent-get-version" "quiet,verbose" \
     "Version \"$version_req\" of \"$package\" was not found among the ENT-private packages" ||
   {
@@ -431,7 +436,7 @@ check-env.npm-registry-package() {
     else
       DEPENDENCY_ERROR "Mandatory dependency not available"
     fi
-    
+
     check_ver "_ent-$package" "$version_req" "--ent-get-version" "quiet,verbose" || {
       PRIVATE_DEPENDENCY_INSTALL_ERROR "Unable to install \"$package\" ($version_def)"
     }
@@ -448,7 +453,7 @@ PARSE_ARGS() {
   args_or_ask -h "$HH" -n -F LENIENT "--lenient///Assumes yes for all yes-no questions" "$@"
   args_or_ask -h "$HH" -n -F VERBOSE "--verbose///Prints more details" "$@"
   args_or_ask -h "$HH" -n -F EXT_MOD "--include-extension-modules///also runs the check-env of the extension modules" "$@"
-  
+
   args_or_ask -h "$HH" -n ENTANDO_K3S_VERSION_OVERRIDE "--k3s-version///overrides the k3s version to use" "$@"
   args_or_ask -h "$HH" -n ENTANDO_NODE_VERSION_OVERRIDE "--node-version///overrides the node version to use" "$@"
   args_or_ask -h "$HH" -n ENTANDO_BUNDLER_VERSION_OVERRIDE "--entando-bundler-version///overrides the entando-bundler to use" "$@"
@@ -460,22 +465,22 @@ PARSE_ARGS() {
   end_help_parsing
 
 
-  FATAL_DEPENDENCY_ERROR() { 
+  FATAL_DEPENDENCY_ERROR() {
     local msg="### DEPENDENCY ERROR"$'\n'
     msg+="### Recommended dependency was not found and cannot be automatically installed."$'\n'
     msg+="### Please install ${1:-it} manually or use --lenient to ignore this error"$'\n'
     echo $'\n'"$msg"$'\n'
-    exit 99; 
+    exit 99;
   }
-  
-  PRIVATE_DEPENDENCY_INSTALL_ERROR() { 
+
+  PRIVATE_DEPENDENCY_INSTALL_ERROR() {
     echo "~"
     _log_e "$1"
     local msg="### DEPENDENCY ERROR"$'\n'
     msg+="### It has not been possible to install a required dependency"$'\n'
     msg+="### Use --lenient to ignore this error"$'\n'
     echo $'\n'"$msg"$'\n'
-    exit 99; 
+    exit 99;
   }
 
   if $LENIENT; then
@@ -493,7 +498,7 @@ PARSE_ARGS() {
   M_KUBE=false
   M_QS=false
   ENTANDO_CLI_CHECKENV_MODE="$ARG1"
-  
+
   case "$ARG1" in
     develop) #H: environment for bundle developers
       M_DEVL=true
