Add "ent app new" command and use it in the quickstart

diff --git a/bin/mod/ent-app b/bin/mod/ent-app
--- a/bin/mod/ent-app
+++ b/bin/mod/ent-app
@@ -18,7 +18,7 @@
   exit 0
 }
 
-DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" > /dev/null 2>&1 && pwd)"
+DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"
 cd "$DIR/../.." || {
   echo "Internal error: unable to find the script source dir" 1>&2
   exit
@@ -35,7 +35,6 @@ RUN() {
 
   show_help_option "$HH" ":main"
   args_or_ask ${HH:+"$HH"} -a -n -- "CMD" '1///%sp command' "$@"
-
   args_or_ask ${HH:+"$HH"} -n -p NAMESPACE "--namespace/ext_ic_id//%sp the kubernetes namespace" "$@"
 
   [[ -n "$HH" && -z "$CMD" ]] && exit
@@ -43,97 +42,93 @@ RUN() {
   show_help_option "$HH" "\"$CMD\""
 
   case "$CMD" in
-    "use") #H: selects the app context that ent should use
-      args_or_ask ${HH:+"$HH"} -n -F "NO_AUTO_LOGIN" "--no-auto-login///Disable auto-login" "$@"
-      args_or_ask ${HH:+"$HH"} -n -F "AUTO_YES" "--yes///Assumes yes for all yes-no questions" "$@"
-      args_or_ask ${HH:+"$HH"} -n -F "AUTO_NO" "--no///Assumes no for all yes-no questions" "$@"
-      args_or_ask ${HH:+"$HH"} -n -F "USE_NO_APPCTX" "--none///Assumes the global application context" "$@"
-      [ -n "$HH" ] && exit 0
-      shift
-      use_app_ctx "$@"
-      app_ctx_auto_login
-      ;;
-    "stop") #H: stops the app associated to the the given app context
-      [ -n "$HH" ] && exit 0
-      if [ -n "$DESIGNATED_VM" ]; then
-        multipass stop "$DESIGNATED_VM"
-      else
-        _log_e 0 "This command only works with managed VMs"
-      fi
+  "use") #H: selects the app context that ent should use
+    show_help_option "$HH" "$CMD"
+    args_or_ask ${HH:+"$HH"} -n -F "NO_AUTO_LOGIN" "--no-auto-login///Disable auto-login" "$@"
+    args_or_ask ${HH:+"$HH"} -n -F "AUTO_YES" "--yes///Assumes yes for all yes-no questions" "$@"
+    args_or_ask ${HH:+"$HH"} -n -F "AUTO_NO" "--no///Assumes no for all yes-no questions" "$@"
+    args_or_ask ${HH:+"$HH"} -n -F "USE_NO_APPCTX" "--none///Assumes the global application context" "$@"
+    [ -n "$HH" ] && exit 0
+    shift
+    APP_LOGIN_URL=""
+    APP_LOGIN_TOKEN=""
+    use_app_ctx "$@"
+    app_ctx_auto_login
+    app_ctx_auto_attach
     ;;
-    "start") #H: starts the app associated to the the given app context
-      [ -n "$HH" ] && exit 0
-      if [ -n "$DESIGNATED_VM" ]; then
-        multipass start "$DESIGNATED_VM"
-      else
-        _log_e 0 "This command only works with managed VMs"
-      fi
+  "new") #H: created a new app context
+    shift
+    new_app_ctx "$@"
     ;;
-    "delete") #H: delete the given app context
-      args_or_ask ${HH:+"$HH"} -n -F "AUTO_YES" "--yes///Assumes yes for all yes-no questions" "$@"
-      [ -n "$HH" ] && exit 0
-      shift
+  "stop") #H: stops the app associated with the the given app context
+    [ -n "$HH" ] && exit 0
+    if [ -n "$DESIGNATED_VM" ]; then
+      multipass stop "$DESIGNATED_VM"
+    else
+      _log_e 0 "This command only works with managed VMs"
+    fi
+    ;;
+  "start") #H: starts the app associated with the the given app context
+    [ -n "$HH" ] && exit 0
+    if [ -n "$DESIGNATED_VM" ]; then
+      multipass start "$DESIGNATED_VM"
+    else
+      _log_e 0 "This command only works with managed VMs"
+    fi
+    ;;
+  "delete") #H: delete the given app context
+    args_or_ask ${HH:+"$HH"} -n -F "AUTO_YES" "--yes///Assumes yes for all yes-no questions" "$@"
+    [ -n "$HH" ] && exit 0
+    shift
+    delete_app_ctx "$@"
+    ;;
+  "list") #H: prints a list of the available app contexts
+    [ -n "$HH" ] && exit 0
+    shift
+    list_app_ctx "$@"
+    ;;
+  "login") #H: logins to an application context using a token
+    [ -n "$HH" ] && exit 0
+    shift
+    login_to_app_ctx "$@"
+    ;;
+  "images") #H: print the images running in the current EntandoApp
+    print_images "$@"
+    ;;
+  "configmap") #H: prints the configmap used to deploy the current EntandoApp
+    print_configmap "$@"
+    ;;
+  "status") #H: prints status information about the current EntandoApp
+    local WATCH
+    determine_namespace ENTANDO_NAMESPACE "$@"
+    args_or_ask ${HH:+"$HH"} -n -p ENTANDO_APPNAME "--appname/ext_ic_id//%sp the application name" "$@"
+    args_or_ask ${HH:+"$HH"} -n -F WATCH "--watch///" "$@"
 
-      if [ -n "$DESIGNATED_VM" ]; then
-        _log_w 0 "This application context is associated to a managed VM"
-        if $AUTO_YES || ask "Should I remove the VM too?"; then
-          multipass delete "$DESIGNATED_VM"
-          _log_i 0 "VM deleted, to completely remove it run multipass purge"
-        fi
-        delete_app_ctx "$THIS_APP_CTX"
-      else
-        delete_app_ctx "$@"
-      fi
+    [ -n "$HH" ] && exit 0
 
-      ;;
-    "list") #H: prints a list of the available app contexts
-      [ -n "$HH" ] && exit 0
-      shift
-      list_app_ctx "$@"
-      ;;
-    "login") #H: logins to an application context using a token
-      [ -n "$HH" ] && exit 0
-      shift
-      login_to_app_ctx "$@"
-      ;;
-    "images") #H: print the images running in the current EntandoApp
-      print_images "$@"
-      ;;
-    "configmap") #H: prints the configmap used to deploy the current EntandoApp
-      print_configmap "$@"
-      ;;
-    "status") #H: prints status information about the current EntandoApp
-      local WATCH
-      determine_namespace ENTANDO_NAMESPACE "$@"
-      args_or_ask ${HH:+"$HH"} -n -p ENTANDO_APPNAME "--appname/ext_ic_id//%sp the application name" "$@"
-      args_or_ask ${HH:+"$HH"} -n -F WATCH "--watch///" "$@"
-
-      [ -n "$HH" ] && exit 0
-
-      if $WATCH; then
-        ent app-info watch "$ENTANDO_NAMESPACE" "$ENTANDO_APPNAME"
-      else
-        ent app-info "$ENTANDO_NAMESPACE" "$ENTANDO_APPNAME"
-      fi
-      ;;
-    "")
-      [ -n "$HH" ] && exit 0
-      _log_i 2 "The current application context is:"
-      echo "$ENTANDO_CURRENT_APP_CTX"
-      _log_i 2 "The available application contexts are:"
-      list_app_ctx "$@"
-      ;;
-    *)
-      [ -n "$HH" ] && exit 0
-      FATAL "Unknown command \"$CMD\""
-      ;;
+    if $WATCH; then
+      ent app-info watch "$ENTANDO_NAMESPACE" "$ENTANDO_APPNAME"
+    else
+      ent app-info "$ENTANDO_NAMESPACE" "$ENTANDO_APPNAME"
+    fi
+    ;;
+  "")
+    [ -n "$HH" ] && exit 0
+    print_current_app_context_name
+    _log_i 2 "The available application contexts are:"
+    list_app_ctx "$@"
+    ;;
+  *)
+    [ -n "$HH" ] && exit 0
+    FATAL "Unknown command \"$CMD\""
+    ;;
   esac
 }
 
 print_configmap() {
   [ -n "$HH" ] && exit 0
-  _kubectl ${NAMESPACE:+-n "$NAMESPACE"} get configmap "entando-docker-image-info" -o yaml \
-    | perl -p0e 's/.*\n(data:.*)/\1/msg' | perl -p0e 's/\n[^ ].*//msg'
+  _kubectl ${NAMESPACE:+-n "$NAMESPACE"} get configmap "entando-docker-image-info" -o yaml |
+    perl -p0e 's/.*\n(data:.*)/\1/msg' | perl -p0e 's/\n[^ ].*//msg'
 }
 
 print_images() {
@@ -145,9 +140,9 @@ print_images() {
   [ -n "$HH" ] && exit 0
   # shellcheck disable=SC2021 disable=SC2155
   local RES=$(
-    _kubectl ${NAMESPACE:+-n "$NAMESPACE"} get pods -o jsonpath="{..image}" \
-      | \tr -s '[[:space:]]' '\n' | \sort -u \
-      | \grep "$FILTER"
+    _kubectl ${NAMESPACE:+-n "$NAMESPACE"} get pods -o jsonpath="{..image}" |
+      \tr -s '[[:space:]]' '\n' | \sort -u |
+      \grep "$FILTER"
   )
   [ -z "$RES" ] && FATAL "Unable fetch the images list"
 
@@ -163,41 +158,52 @@ print_images() {
 use_app_ctx() {
   # shellcheck disable=SC2034
   local application_context
-  local apps_base_dir="$ENTANDO_HOME/apps/"
+  local apps_base_dir="$ENTANDO_HOME/apps"
 
   $USE_NO_APPCTX && application_context="--none"
   args_or_ask ${HH:+"$HH"} -a -p -n -- "application_context" '1///%sp application context (or --none)' "$@"
 
+  ENTANDO_CURRENT_APP_CTX=""
+  # shellcheck disable=SC2034
+  ENTANDO_CURRENT_APP_CTX_HOME=""
+
   (
-    if [ "$application_context" = "" ]; then
-      __cd "$apps_base_dir"
-      # shellcheck disable=SC2035
-      map-from-stdin "application_context" $'\n\r' < <(ls -d *)
-      args_or_ask__a_map "application_context" -a ${HH:+"$HH"} "APP_CTX" "1" "Select the application context" "$@"
-      local app_dir="$ENTANDO_HOME/apps/$APP_CTX/"
+    if $USE_NO_APPCTX; then
+      save_cfg_value "ENTANDO_CURRENT_APP_CTX" "" "$ENTANDO_GLOBAL_CFG"
+      save_cfg_value "ENTANDO_CURRENT_APP_CTX_HOME" "" "$ENTANDO_GLOBAL_CFG"
+    else
+      # shellcheck disable=SC2030
+      local APP_CTX
+      if [ "$application_context" = "" ]; then
+        __cd "$apps_base_dir"
+        # shellcheck disable=SC2035
+        map-from-stdin application_context $'\n\r' < <(ls -d *)
+        args_or_ask_from_list application_context -m -a ${HH:+"$HH"} APP_CTX 1 "any" \
+          "application context" "Select the application context" "$@"
+      else
+        APP_CTX="$application_context"
+      fi
+
+      local app_dir="$ENTANDO_HOME/apps/$APP_CTX"
 
       if [ ! -d "$app_dir" ]; then
         _log_w 0 "Application context \"$APP_CTX\" not found"
-        _log_i 0 "Application context \"$APP_CTX\" created"
         $AUTO_NO && EXIT_UE "Auto Interrupted due to auto-no"
         $AUTO_YES || ask "Should I create it?" || EXIT_UE "User interrupted"
-        mkdir -p "${app_dir}"
-        cp -r "$ENT_WORK_DIR" "${app_dir}" || true
-        _log_i 0 "New configuration and state created under \"$APP_CTX\""
+        new_app_ctx "$APP_CTX"
       fi
       save_cfg_value "ENTANDO_CURRENT_APP_CTX" "${APP_CTX}" "$ENTANDO_GLOBAL_CFG"
       save_cfg_value "ENTANDO_CURRENT_APP_CTX_HOME" "${app_dir}" "$ENTANDO_GLOBAL_CFG"
     fi
 
-    if [ "$application_context" = "--none" ]; then
-      save_cfg_value "ENTANDO_CURRENT_APP_CTX" "" "$ENTANDO_GLOBAL_CFG"
-      save_cfg_value "ENTANDO_CURRENT_APP_CTX_HOME" "" "$ENTANDO_GLOBAL_CFG"
-    fi
-
     true
   ) && {
     reload_cfg "$ENTANDO_GLOBAL_CFG"
-    activate_application_workdir
+    if [ -n "$ENTANDO_CURRENT_APP_CTX" ]; then
+      activate_application_workdir
+    else
+      activate_ent_default_workdir
+    fi
     save_cfg_value "THIS_APP_CTX" "${ENTANDO_CURRENT_APP_CTX}"
     ENT_KUBECTL_CMD=""
     ENABLE_AUTOLOGIN=""
@@ -206,37 +212,119 @@ use_app_ctx() {
   }
 }
 
+new_app_ctx() {
+  local LOGIN_URL LOGIN_TOKEN ATTACH_VM
+
+  HH="$(parse_help_option "$@")"
+  show_help_option "$HH" ":main"
+
+  args_or_ask ${HH:+"$HH"} -a APP_CTX "1/ext_ic_id//%sp application context name" "$@"
+  # shellcheck disable=SC2031
+  [ -z "$APP_CTX" ] && FATAL "Please provide the application context"
+
+  args_or_ask ${HH:+"$HH"} -a ENTANDO_APPNAME "2/ext_ic_id/$APP_CTX/%sp EntandoApp name" "$@"
+  args_or_ask ${HH:+"$HH"} -a DEFAULT_NAMESPACE "3/ext_ic_id/$APP_CTX/%sp namespace name" "$@"
+
+  args_or_ask -n ${HH:+"$HH"} ATTACH_VM "--attach-vm/ext_ic_id?//%sp name of the vm to attach (if applicable)" "$@"
+  args_or_ask -n ${HH:+"$HH"} MAN_CMD "--kubecmd/ext_ic_id?//%sp the kubernetes management command (or nothing)" "$@"
+  args_or_ask -n ${HH:+"$HH"} LOGIN_URL "--login-url///%sp the login url (if applicable)" "$@"
+  args_or_ask -n  ${HH:+"$HH"} LOGIN_TOKEN "--login-token///%sp the login token (if applicable)" "$@"
+
+  if [ -z "$ATTACH_VM" ]; then
+    set_or_ask MAN_CMD "$MAN_CMD" "%sp the kubernetes management command (or nothing)" "$MAN_CMD" "assert_ext_ic_id?"
+    set_or_ask LOGIN_URL "$LOGIN_URL" "%sp the login url (if applicable)" "$LOGIN_URL" "assert_url?"
+    if [ -n "$LOGIN_URL" ]; then
+      set_or_ask LOGIN_TOKEN "$LOGIN_TOKEN" "%sp the login token (if applicable)" "$LOGIN_TOKEN" ""
+    fi
+  fi
+
+  [ -n "$HH" ] && exit 0
+
+  local APP_CTX="$1"
+  local app_dir="$ENTANDO_HOME/apps/$APP_CTX"
+
+  [ -d "${app_dir}" ] && FATAL "Application context \"$APP_CTX\" already exists under dir: \"$app_dir\""
+
+  mkdir -p "${app_dir}/w"
+  _log_i 0 "Application context \"$APP_CTX\" created"
+  #cp -r "$ENT_WORK_DIR" "${app_dir}" || true
+  #_log_i 0 "New configuration and state created under \"$APP_CTX\""
+  local CFG="$app_dir/w/.cfg"
+
+  save_cfg_value ENTANDO_APPNAME "$ENTANDO_APPNAME" "$CFG"
+  save_cfg_value DEFAULT_NAMESPACE "$DEFAULT_NAMESPACE" "$CFG"
+  save_cfg_value ENTANDO_NAMESPACE "$DEFAULT_NAMESPACE" "$CFG"
+
+  if [ -n "$ATTACH_VM" ]; then
+    save_cfg_value DESIGNATED_VM "$ATTACH_VM" "$CFG"
+  else
+    if [ -n "$MAN_CMD" ]; then
+      save_cfg_value ENT_KUBECTL_CMD "$MAN_CMD" "$CFG"
+    fi
+
+    if [ -n "$LOGIN_URL" ]; then
+      save_cfg_value APP_LOGIN_URL "$LOGIN_URL" "$CFG"
+      save_cfg_value APP_LOGIN_TOKEN "$LOGIN_TOKEN" "$CFG"
+    fi
+  fi
+}
+
 delete_app_ctx() {
   # shellcheck disable=SC2034
   local application_context
-  local apps_base_dir="$ENTANDO_HOME/apps/"
+  local apps_base_dir="$ENTANDO_HOME/apps"
+
+  local APP_CTX
+  __cd "$apps_base_dir"
+  # shellcheck disable=SC2035
+  map-from-stdin "application_context" $'\n\r' < <(ls -d *)
+  args_or_ask_from_list "application_context" -m -a ${HH:+"$HH"} APP_CTX 1 "any" \
+    "application context" "Select the application context" "$@"
+  [ ! -d "$APP_CTX" ] && FATAL "Application not found"
+  [ ! -d "$APP_CTX/w" ] && FATAL "Invalid application context dir"
 
   (
-    __cd "$apps_base_dir"
-    # shellcheck disable=SC2035
-    map-from-stdin "application_context" $'\n\r' < <(ls -d *)
-    args_or_ask__a_map "application_context" -a ${HH:+"$HH"} "APP_CTX" "1" "Select the application context" "$@"
-    [ ! -d "$APP_CTX" ] && FATAL "Application not found"
-    [ ! -d "$APP_CTX/w" ] && FATAL "Invalid application context dir"
     _log_w 0 "Application context \"$APP_CTX\" found"
     $AUTO_YES || ask "Should I really delete it?" || EXIT_UE "User interrupted"
+    ##########
+    # shellcheck disable=SC2034
+    # shellcheck disable=SC2030
+    (
+      ENTANDO_CURRENT_APP_CTX="$APP_CTX"
+      ENTANDO_CURRENT_APP_CTX_HOME="$ENTANDO_HOME/apps/$ENTANDO_CURRENT_APP_CTX"
+      activate_application_workdir
+      reload_cfg
+
+      if [ -n "$DESIGNATED_VM" ]; then
+        _log_w 0 "This application context is associated with a managed VM"
+        if $AUTO_YES || ask "Should I remove the VM too?"; then
+          multipass delete "$DESIGNATED_VM"
+          _log_i 0 "VM deleted, to completely remove it run \"multipass purge\""
+        fi
+      fi
+    )
+    ##########
     rm -rf "$APP_CTX"
     _log_i 0 "Application context \"$APP_CTX\" deleted"
 
-    save_cfg_value "THIS_APP_CTX" ""
     save_cfg_value "ENTANDO_CURRENT_APP_CTX" "" "$ENTANDO_GLOBAL_CFG"
     save_cfg_value "ENTANDO_CURRENT_APP_CTX_HOME" "" "$ENTANDO_GLOBAL_CFG"
     true
   ) && {
     reload_cfg "$ENTANDO_GLOBAL_CFG"
-    _log_i 0 "Current application context: $THIS_APP_CTX"
+    if [ "$APP_CTX" = "$THIS_APP_CTX" ]; then
+      THIS_APP_CTX=""
+      save_cfg_value "ENTANDO_CURRENT_APP_CTX" "" "$ENTANDO_GLOBAL_CFG"
+      save_cfg_value "ENTANDO_CURRENT_APP_CTX_HOME" "" "$ENTANDO_GLOBAL_CFG"
+    fi
+    print_current_app_context_name
   }
 }
 
 list_app_ctx() {
   # shellcheck disable=SC2034
   local application_context
-  local apps_base_dir="$ENTANDO_HOME/apps/"
+  local apps_base_dir="$ENTANDO_HOME/apps"
 
   (
     __cd "$apps_base_dir"
@@ -251,7 +339,7 @@ list_app_ctx() {
 
 login_to_app_ctx() {
   local CACHED
-  args_or_ask ${HH:+"$HH"} -F -- "CACHED" "--cached//$C_QUICKSTART_DEFAULT_RELEASE/%sp authentication token" "$@"
+  args_or_ask ${HH:+"$HH"} -F -- "CACHED" "--cached///%sp authentication token" "$@"
 
   if ! $CACHED; then
     args_or_ask ${HH:+"$HH"} -a -p -- "APP_LOGIN_URL" '1///%sp URL' "$@"
@@ -268,13 +356,19 @@ login_to_app_ctx() {
 }
 
 app_ctx_auto_login() {
-  if ! $NO_AUTO_LOGIN  && login_supported && [[ -n "$APP_LOGIN_URL" && -n "$APP_LOGIN_TOKEN" ]]; then
+  if ! $NO_AUTO_LOGIN && login_supported && [[ -n "$APP_LOGIN_URL" && -n "$APP_LOGIN_TOKEN" ]]; then
     _log_i 0 "Autologin to \"$APP_LOGIN_URL\""
     _kubectl login "$APP_LOGIN_URL" --token="$APP_LOGIN_TOKEN" || {
       _log_w 0 "AutoLogin failed, clearing the credentials cache"
       APP_LOGIN_TOKEN=""
       save_cfg_value "APP_LOGIN_TOKEN" ""
     }
+  fi
+}
+
+app_ctx_auto_attach() {
+  if [ -n "$DESIGNATED_VM" ]; then
+    ent attach-vm "$DESIGNATED_VM"
   fi
 }
 
diff --git a/bin/mod/ent-prj b/bin/mod/ent-prj
--- a/bin/mod/ent-prj
+++ b/bin/mod/ent-prj
@@ -75,6 +75,7 @@ RUN() {
         ;;
       "uninstall") #H: generates the CR and deploys it to the current application context
         HH="$(parse_help_option "$@")"
+        args_or_ask ${HH:+"$HH"} -n -F "ENTANDO_OPT_YES_FOR_ALL" "--yes///Assumes yes for all yes-no questions" "$@"
         args_or_ask -n -F ${HH:+"$HH"} "BE_PURGE" \
           '--purge-be///also purge the backend' "$@"
         args_or_ask -n -F ${HH:+"$HH"} "ECR_UNDEPLOY" \
@@ -89,9 +90,9 @@ RUN() {
         $BE_PURGE && be_purge_k8s
         $ECR_UNDEPLOY && prj_ecr_unregister_bundle
         ;;
-      # ~~~~~~~~~~~~~~~~~~~~
-      #H:> PUB SYSTEM:
-      # ~~~~~~~~~~~~~~~~~~~~
+        # ~~~~~~~~~~~~~~~~~~~~
+        #H:> PUB SYSTEM:
+        # ~~~~~~~~~~~~~~~~~~~~
       "pbs-init") #H: (url, username, email) initializes the publication system
         require_develop_checked
         #require_initialized_dir
@@ -135,6 +136,18 @@ RUN() {
         #H:> BACKEND:
         # ~~~~~~~~~~~~~~~~~~~~
       "be-build" | "bb") #H: (mvn-params) builds and package the backend
+        HH="$(parse_help_option "$@")"
+        show_help_option "$HH"
+        OPT_CLEAN="clean"
+        args_or_ask -n -f ${HH:+"$HH"} '--no-clean///avoid cleaning the build artifacts before the build' "$@" && {
+          OPT_CLEAN=""
+        }
+        OPT_TESTS=""
+        args_or_ask -n -f ${HH:+"$HH"} '--no-tests///avoid cleaning the build artifacts before the build' "$@" && {
+          OPT_TESTS="-Dmaven.test.skip=true"
+        }
+        [ -n "$HH" ] && return 0
+
         require_develop_checked
         require_ent_project_dir
         be_build "$@"
@@ -148,7 +161,7 @@ RUN() {
       "be-update-deployment" | "brp") #H: list the pods related to this bundle project
         require_develop_checked
         require_ent_project_dir
-        be_restart_pods
+        be_restart_pods 0
         ;;
       "be-purge") #H: list the pods related to this bundle project
         require_develop_checked
@@ -165,9 +178,9 @@ RUN() {
         local restart_pods_after
         args_or_ask -n -f ${HH:+"$HH"} \
           '--update-deployment///restarts the pods related to this bundle project' "$@" && {
-            restart_pods_after=3
-          }
-        args_or_ask -n ${HH:+"$HH"} "restart_pods_after" \
+          restart_pods_after=3
+        }
+        args_or_ask -n -p ${HH:+"$HH"} "restart_pods_after" \
           '--update-deployment-after/num//restarts the pods related to this bundle project' "$@"
         [ -n "$HH" ] && return 0
 
@@ -235,8 +248,8 @@ prj_ecr_install() {
     DATA="${DATA/"@@"/}"
   fi
 
-  ecr-bundle-action "" "POST" "install" "$INGRESS_URL" "$TOKEN" "$ENT_PRJ_NAME" "$DATA" 2>/dev/null \
-    || return $?;
+  ecr-bundle-action "" "POST" "install" "$INGRESS_URL" "$TOKEN" "$ENT_PRJ_NAME" "$DATA" &> /dev/null \
+    || return $?
   _log_i 0 "Installation of bundle \"$ENT_PRJ_NAME\" started"
 
   ecr-watch-installation-result "install" "$INGRESS_URL" "$TOKEN" "$ENT_PRJ_NAME"
@@ -246,7 +259,7 @@ prj_ecr_uninstall() {
   local INGRESS_URL TOKEN
   ecr-prepare-action INGRESS_URL TOKEN
   _log_i 0 "Uninstallation of bundle \"$ENT_PRJ_NAME\" started"
-  ecr-bundle-action "" "POST" "uninstall" "$INGRESS_URL" "$TOKEN" "$ENT_PRJ_NAME" 2>/dev/null || return $?
+  ecr-bundle-action "" "POST" "uninstall" "$INGRESS_URL" "$TOKEN" "$ENT_PRJ_NAME" &> /dev/null || return $?
   ecr-watch-installation-result "uninstall" "$INGRESS_URL" "$TOKEN" "$ENT_PRJ_NAME"
 }
 
@@ -419,7 +432,7 @@ be_build() {
   be_update_plugin_descriptor
 
   # shellcheck disable=SC2015
-  ./mvnw -Pprod clean package jib:dockerBuild "$@" && {
+  ./mvnw -Pprod ${OPT_CLEAN:+"$OPT_CLEAN"} ${OPT_TESTS:+"$OPT_TESTS"} package jib:dockerBuild && {
     echo ""
     _log_i 0 "Built image \"$IMAGE_FQNAME\""
     true
@@ -430,7 +443,7 @@ be_build() {
 
 be_update_plugin_descriptor() {
   local PLUGIN_BUNDLE_DIR
-  PLUGIN_BUNDLE_DIR="$(grep -- "- plugins/.*"  "bundle/$C_BUNDLE_DESCRIPTOR_FILE_NAME" | perl -pe "s|\s*- (.*)|\1|")"
+  PLUGIN_BUNDLE_DIR="$(grep -- "- plugins/.*" "bundle/$C_BUNDLE_DESCRIPTOR_FILE_NAME" | perl -pe "s|\s*- (.*)|\1|")"
   [ -z "$PLUGIN_BUNDLE_DIR" ] && FATAL "Unable to determine the plugin bundle dir"
   PLUGIN_DESCRIPTOR="bundle/$PLUGIN_BUNDLE_DIR"
   _sed_in_place "s|^\(.*\)image:.*|\1image: $IMAGE_FQNAME|" "$PLUGIN_DESCRIPTOR"
@@ -439,7 +452,7 @@ be_update_plugin_descriptor() {
 be_list_pods() {
   print_current_app_context_name
   get_be_info
-  get_pods_list "$IMAGE_FQNAME_NAME"
+  get_pods_list "$IMAGE_FQNAME_ORG-$IMAGE_FQNAME_NAME"
 }
 
 be_restart_pods() {
@@ -447,10 +460,8 @@ be_restart_pods() {
   print_current_app_context_name
   get_be_info
   local pods
-  pods="$(get_pods_list "$IMAGE_FQNAME_NAME" | tail -n +2 | cut -d' ' -f 1)"
-  # shellcheck disable=SC2034
-  #WAS_ASSUMING_NAMESPACE_PRINTED=true
-  [ "${#pods}" -eq 0  ] && {
+  pods="$(get_pods_list "$IMAGE_FQNAME_ORG-$IMAGE_FQNAME_NAME" | grep "server-deployment" | cut -d' ' -f 1)"
+  [ "${#pods}" -eq 0 ] && {
     _log_i 0 "Restart pods was not able to find any pod in the current app context"
     return 0
   }
@@ -470,27 +481,65 @@ be_purge_k8s() {
   ask "Should I proceed?" || EXIT_UE "User interrupted"
   del_resource "EntandoPlugin" "$pn"
   del_resource "deployment" "$pn"
+  del_resource "pod" "$pn"
   del_resource "service" "$pn"
   del_resource "secret" "$pn"
   del_resource "ingress" "$pn"
+  _log_i 0 "Checking the deletion progress.."
+  wait_plugin_resources_deletion "deployment" "service" "ingress" "pod"
   _log_i 0 "done."
 }
 
 del_resource() {
-  if _kubectl delete "$1" -lEntandoPlugin="$pn"; then
-    _log_d 1 "$1 of \"$2\" deleted"
+  local type="$1"
+  local pn="$2"
+  local res
+  case "$type" in
+    "EntandoPlugin")
+      _kubectl delete "$type" "$pn"
+      res=$?
+      ;;
+    "secret" | "pod")
+      # shellcheck disable=SC2046
+      _kubectl delete "$type" $(
+        _kubectl get "$type" -o "custom-columns=NAME:.metadata.name" | grep -E "^$pn|quickstart-$pn"
+      )
+      res=$?
+      ;;
+    *)
+      _kubectl delete "$type" -lEntandoPlugin="$pn"
+      res=$?
+      ;;
+  esac
+
+  if [ "$res" -eq 0 ]; then
+    _log_d 1 "$type of \"$pn\" deleted"
   else
-    _log_w 0 "Error deleting the $1 of \"$2\""
+    _log_w 0 "Error deleting the $type of \"$pn\""
   fi
+}
+
+wait_plugin_resources_deletion() {
+  local n
+  for type in "$@"; do
+    while true; do
+      n="$(_kubectl get "$type" -lEntandoPlugin="$pn" 2> /dev/null | wc -l)"
+      if [ "$n" -eq 0 ]; then
+        echo -e "No resource found of type $type for the plugin"
+        break
+      else
+        printf "\r                                                                  \r"
+        printf "Waiting for %s plugin resource(s) of type %s to be deleted" "$n" "$type"
+        sleep 3
+      fi
+    done
+  done
 }
 
 get_pods_list() {
   local pn="$1"
-  #local pn="avdev4j-pet-manager"
   _kubectl get pods \
-    -lEntandoResourceKind=EntandoPlugin \
     -lEntandoPlugin="$pn" \
-    -l=deployment="$pn"-server \
     -o "custom-columns=NAME:.metadata.name,STATUS:.status.phase"
 }
 # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
@@ -668,7 +717,11 @@ init_pub() {
   initialize_publication_git_repository "$@"
   ensure_valid_location_for_git_publication :initialized "$@"
 
-  _log_i 1 "bundle publication repository initialized"
+  if [ $? -eq 0 ]; then
+    _log_i w "bundle publication repository was not properly initialized"
+  else
+    _log_i 1 "bundle publication repository initialized"
+  fi
 }
 
 initialize_publication_git_repository() {
@@ -764,7 +817,6 @@ ensure_valid_location_for_git_publication() {
       _log_w 1 "A remote master has been detected"
       ask "Should I import it?"
 
-
       if [ $? -ne 0 ]; then
         # USER CHOSE TO NOT IMPORT
         if $FORCE; then
@@ -808,26 +860,26 @@ ensure_valid_location_for_git_publication() {
 
           # IMPORT
           _log_d 1 "Checking out the remote master"
-          git branch -m master master_old 1> /dev/null 2>&1
-          git branch -D master 1> /dev/null 2>&1
+          git branch -m master master_old &> /dev/null
+          git branch -D master &> /dev/null
           git fetch origin master
-          git checkout -b master origin/master
-          git branch -D master_old 1> /dev/null 2>&1
+          git checkout -b master origin/master || FATAL "Error checking out the remote master"
+          git branch -D master_old &> /dev/null
         fi
       fi
     fi
 
-    if [[ "$MODE" = "NORMAL" || "$MODE" = "OVERRIDE" ]]; then
+    if [[ "$MODE" == "NORMAL" || "$MODE" == "OVERRIDE" ]]; then
       # there is no master on remote
       echo "" > .gitignore
       git add .gitignore descriptor.yaml
       ls plugins/*.yaml 1> /dev/null && git add plugins/*.yaml
-      git commit -m "init"
-      git checkout -b master
+      git commit -m "init" || return $?
+      git checkout -b master &> /dev/null
       if [ "$MODE" = "OVERRIDE" ]; then
-        git push --set-upstream origin master --force
+        git push --set-upstream origin master --force || FATAL "Error pushing the base initialization"
       else
-        git push --set-upstream origin master
+        git push --set-upstream origin master || FATAL "Error pushing the base initialization"
       fi
     fi
 
