Support for talking to remote kubernetes instances

diff --git a/bin/ent-diag b/bin/ent-diag
--- a/bin/ent-diag
+++ b/bin/ent-diag
@@ -3,32 +3,26 @@
 
 [ "$1" = "-h" ] && echo -e "Runs some diagnostic and collects the related info in a tgz file | Syntax: ${0##*/} namespace" && exit 0
 
-NS="$1"
-[ "$NS" == "" ] && NS="$ENTANDO_NAMESPACE"
-[ "$NS" == "" ] && echo "please provide the namespace name" 1>&2 && exit 1
+DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" > /dev/null 2>&1 && pwd)"
+cd "$DIR/.." || {
+  echo "Internal error: unable to find the script source dir" 1>&2
+  exit
+}
 
-TT="$PWD/entando-diagdata"
+
+. s/_base.sh
+
+args_or_ask -n -f '--help' "$@" && { HH="-h"; echo "> Parameters:"; }
+args_or_ask -p $HH "NS" '--namespace/id/entando/Please provide the namespace' "$@"
+
+# NODES
+NN="entando-diagdata-$(date -u '+%Y-%m-%dT%H:%M:%S%z')"
+TT="$HOME/.entando/reports/$NN"
 mkdir -p "$TT"
-cd "$TT" || FATAL "Unable to enter di \"$TT\""
+__cd "$TT"
 
-# KUBECTL
-
-if [ -n "$ENTANDO_KUBECTL" ]; then
-    _kubectl() { "$ENTANDO_KUBECTL" "$@"; }
-else
-  if command -v "k3s" > /dev/null; then
-    if $OS_WIN; then
-      _kubectl() { k3s kubectl "$@"; }
-    else
-      _kubectl() { sudo k3s kubectl "$@"; }
-    fi
-  else
-    _kubectl() { kubectl "$@"; }
-  fi
-fi
-
-_kubectl get nodes
-echo "" >basics.txt
+echo "# $NN" >basics.txt
+_kubectl get nodes >basics.txt
 
 # DNS rebinding protection TEST
 echo "## DNS rebinding protection TEST"
@@ -62,10 +56,10 @@ for pod in $(_kubectl get pods -n "$NS" | awk 'NR>1' | awk '{print $1}'); do
   done
 done
 
-echo "> Collected diagdata available under \"./entando-diagdata\" for consultation"
+echo "> Collected diagdata available under \"$TT\" for consultation"
 
 cd ..
 set +e
-tar cfz entando-diagdata.tgz "entando-diagdata"
+tar cfz entando-diagdata.tgz "$NN"
 
-echo "> Collected diagdata available into archive \"entando-diagdata.tgz\""
+echo "> Collected diagdata available in archive \"${TT}.tgz\""
diff --git a/hr/auto b/hr/auto
--- a/hr/auto
+++ b/hr/auto
@@ -2,20 +2,19 @@
 
 C_QUICKSTART_DEFAULT_RELEASE="quickstart"
 
-[ -z "$ENTANDO_CLI_VERSION" ] && ENTANDO_CLI_VERSION="develop" && echo "Assuming ENTANDO_CLI_VERSION=\"$ENTANDO_CLI_VERSION\""
 [ -z "$ENTANDO_NAMESPACE" ] && ENTANDO_NAMESPACE="entando" && echo "Assuming ENTANDO_NAMESPACE=\"$ENTANDO_NAMESPACE\""
 [ -z "$ENTANDO_APPNAME" ] && ENTANDO_APPNAME="quickstart" && echo "Assuming ENTANDO_APPNAME=\"$ENTANDO_APPNAME\""
 [ -z "$ENTANDO_WITH_VM" ] && ENTANDO_WITH_VM="true" && echo "Assuming ENTANDO_WITH_VM=\"$ENTANDO_WITH_VM\""
 [ -z "$ENTANDO_RELEASE" ] && ENTANDO_RELEASE="$C_QUICKSTART_DEFAULT_RELEASE" && echo "Assuming ENTANDO_RELEASE=\"$ENTANDO_RELEASE\""
 [ -z "$ENTANDO_OPT_YES_FOR_ALL" ] && ENTANDO_OPT_YES_FOR_ALL=true  && echo "Assuming ENTANDO_OPT_YES_FOR_ALL=\"$ENTANDO_OPT_YES_FOR_ALL\""
 
-if [ "$ENTANDO_CLI_VERSION" = "develop" ] || [[ "$ENTANDO_CLI_VERSION" =~ ^exp-.+ ]]; then
+if [[ "$ENTANDO_CLI_VERSION" = "develop" || "$ENTANDO_CLI_VERSION" =~ ^exp-.+ ]]; then
   rm -rf "$HOME/.entando/ent/$ENTANDO_RELEASE/cli/$ENTANDO_CLI_VERSION/"
 fi
 
 if [ -z "$ENTANDO_DEV_TTY" ]; then
   if [ -t 0 ]; then
-    ENTANDO_DEV_TTY="$(tty)"
+    ENTANDO_DEV_TTY="-"
   else
     case "$OSTYPE" in
       darwin*) ENTANDO_DEV_TTY="-";;
@@ -29,6 +28,18 @@ if [ "$1" = "--local-test" ]; then
   . s/essentials.sh
   . activate --force
 else
+
+  if [ -z "$ENTANDO_CLI_VERSION" ]; then
+    echo "$ENTANDO_CLI_VERSION";
+
+    ENTANDO_CLI_VERSION="$(
+      source /dev/stdin <<<"$(curl "https://raw.githubusercontent.com/entando/entando-releases/$ENTANDO_RELEASE/manifest" 2> /dev/null)";
+      echo "$ENTANDO_CLI_VERSION";
+    )"
+
+    [ -z "$ENTANDO_CLI_VERSION" ] && echo "Unable to determine the CLI version of release \"$ENTANDO_RELEASE\"" 1>&2 && exit 99
+  fi
+
   bash <(curl "https://raw.githubusercontent.com/entando/entando-cli/$ENTANDO_CLI_VERSION/auto-install") \
     --cli-version="$ENTANDO_CLI_VERSION" --release="$ENTANDO_RELEASE"
 
@@ -65,7 +76,7 @@ else
   echo "Assuming SIMPLE INSTALLATION MODE"
 fi
 
-if [ "$ENTANDO_WITH_VM" == "true" ] || [ "$ENTANDO_WITH_VM" == "multipass" ]; then
+if [[ "$ENTANDO_WITH_VM" = "true"  || "$ENTANDO_WITH_VM" == "multipass" ]]; then
   WITH_VM=true
 else
   WITH_VM=false
@@ -98,7 +109,7 @@ cat << EOF > "$T"
   ent-quickstart $P_ENTANDO_INST_MODE ${NNOPTS[@]} "$ENTANDO_NAMESPACE" "$ENTANDO_APPNAME"
 EOF
 
-if [[ -t 0 || "$ENTANDO_DEV_TTY" = "-" ]]; then
+if [ "$ENTANDO_DEV_TTY" = "-" ]; then
   bash "$T"
 else
   bash "$T" < "$ENTANDO_DEV_TTY"
