Fixed support fir private installation of jhipster

diff --git a/bin/ent-jhipster b/bin/ent-jhipster
--- a/bin/ent-jhipster
+++ b/bin/ent-jhipster
@@ -2,10 +2,12 @@
 WD="$PWD"
 DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"
 cd "$DIR/.." || {
-  echo "Internal error: unable to find the script source dir"
+  echo "Internal error: unable to find the script source dir" 1>&2
   exit
 }
 . s/_base.sh
 
 cd "$WD" || FATAL "Unable to access the current dir: $WD"
+
+print_entando_banner
 ent-jhipster "$@"
