General reformat and refactor

diff --git a/bin/ent-prj b/bin/ent-prj
--- a/bin/ent-prj
+++ b/bin/ent-prj
@@ -1,6 +1,6 @@
 #!/bin/bash
 
-DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"
+DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" > /dev/null 2>&1 && pwd)"
 cd "$DIR/.." || {
   echo "Internal error: unable to find the script source dir" 1>&2
   exit
@@ -141,7 +141,7 @@ push_docker() {
 }
 
 push_git() {
-  ensure_valid_location
+  ensure_valid_location_for_git_publication
 
   [ "$1" == "--force" ] && {
     shift
@@ -151,7 +151,7 @@ push_git() {
   set_or_ask "VERSION_NUMBER" "$1" "%sp %var" "" "assert_fdn"
   set_or_ask "VERSION_COMMENT" "$2" "%sp %var" "$VERSION_NUMBER  - $(date -u '+%Y-%m-%dT%H:%M:%S%z')" "assert_nn"
 
-  cd bundle >/dev/null || FATAL "internal error"
+  cd bundle > /dev/null || FATAL "internal error"
 
   if [ ! "$(git status --porcelain)" ]; then
     ask "No change detected; Should I proceed anyway?" || EXIT_UE "User interrupted"
@@ -160,11 +160,11 @@ push_git() {
     git commit -m "$VERSION_COMMENT"
   fi
 
-  git fetch --tags 1>/dev/null
+  git fetch --tags 1> /dev/null
 
   if git tag | grep -q -F "$VERSION_NUMBER"; then
     if $FORCE; then
-      git tag -d "$VERSION_NUMBER" 2>/dev/null 1>&2
+      git tag -d "$VERSION_NUMBER" 2> /dev/null 1>&2
     else
       FATAL "Version \"$VERSION_NUMBER\" already exists"
     fi
@@ -185,8 +185,8 @@ push_git() {
       _log_w 1 "Unable to push to the remote repository, reason; REMOTE HISTORY NOT COMPATIBLE"
       _log_w 1 "I'll try to fix it"
 
-      git fetch origin master &&
-        git rebase -Xtheirs origin/master
+      git fetch origin master \
+        && git rebase -Xtheirs origin/master
 
       RES="$(git push 2>&1)"
       RV=$?
@@ -204,7 +204,7 @@ push_git() {
     fi
   fi
 
-  git push --tags --force 2>/dev/null
+  git push --tags --force 2> /dev/null
   RV=$?
   if [ $RV -ne 0 ]; then
     _log_e 1 "Error pushing the version tag"
@@ -229,7 +229,9 @@ generate_project() {
   JDLT_FILE="$ENT_HOME/res/$TEMPLATE_ID.jdlt"
   cp "$JDLT_FILE" "prj-generation.jdl~"
 
-  for V in $(pre_parse_jdlt "$JDLT_FILE"); do   # <= don't use read here
+  for V in $(# <= don't use read here
+    pre_parse_jdlt "$JDLT_FILE"
+  ); do
     V="$V/"
     val_name="$(echo "$V" | cut -d'/' -f 1)"
     val_type="$(echo "$V" | cut -d'/' -f 2)"
@@ -284,23 +286,24 @@ generate_project() {
   #  echo bundle >> .gitignore
 
   generate_ent_project_file
-  save_cfg_value "PRJ_NAME" "$PRJ_NAME" ".ent-prj"
+  save_cfg_value "PRJ_NAME" "$PRJ_NAME" "$C_ENT_PRJ_FILE"
 
   echo ""
   ask "Do you want to commit everything in a new local git repository?" && {
-    init_project__commit_all
+    init_project__commit_all "publication to the frontend repository"
   }
 
   _log_i 1 "Done."
 }
 
-# shellcheck disable=SC2120
+# shellcheck disable=SC2155
 init_project__commit_all() {
-  local PRJ_USER_NAME="$(git config --global user.name)"
-  local PRJ_USER_EMAIL="$(git config --global user.email)"
+  local desc="$1"
+  local prj_user_name="$(git config --global user.name)"
+  local prj_user_email="$(git config --global user.email)"
   local user_global=false
 
-  if [ -n "$PRJ_USER_NAME" ] && [ -n "$PRJ_USER_EMAIL" ]; then
+  if [ -n "$prj_user_name" ] && [ -n "$prj_user_email" ]; then
     if ask "Do you want to use you global git user?"; then
       user_global=true
     fi
@@ -309,11 +312,11 @@ init_project__commit_all() {
   if $user_global; then
     git init
   else
-    set_or_ask "PRJ_USER_NAME" "$1" "Please provide the git user name" "$PRJ_USER_NAME" "assert_spc_id"
-    set_or_ask "PRJ_USER_EMAIL" "$2" "Please provide the git user email" "$PRJ_USER_EMAIL" "assert_email"
+    set_or_ask "FE_PUB_USER_NAME" "" "Please provide the user name for the $desc" "$prj_user_name" "assert_ext_ic_id"
+    set_or_ask "FE_PUB_USER_EMAIL" "" "Please provide the user email for the $desc" "$prj_user_email" "assert_email"
     git init
-    git config user.name "$PRJ_USER_NAME"
-    git config user.email "$PRJ_USER_EMAIL"
+    git config user.name "$FE_PUB_USER_NAME"
+    git config user.email "$FE_PUB_USER_EMAIL"
   fi
 
   _log_i 1 "Committing the generated files.."
@@ -323,25 +326,25 @@ init_project__commit_all() {
 # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 init_pub() {
   mkdir -p bundle
-  ensure_valid_location
+  ensure_valid_location_for_git_publication
 
-  PUB_USER_NAME="$(git config user.name 2>/dev/null)"
-  PUB_USER_EMAIL="$(git config user.email 2>/dev/null)"
+  PUB_USER_NAME="$(git config user.name 2> /dev/null)"
+  PUB_USER_EMAIL="$(git config user.email 2> /dev/null)"
 
-  read_missing_pub_info_from_project
+  read_missing_pub_info_from_project_sources_git
 
   set_or_ask "URL_OF_ORIGIN" "$1" "Please provide the URL of the publication repository" "" "assert_url"
-  set_or_ask "PUB_USER_NAME" "$2" "%sp Git %var" "$PUB_USER_NAME" "assert_spc_id"
+  set_or_ask "PUB_USER_NAME" "$2" "%sp Git %var" "$PUB_USER_NAME" "assert_ext_ic_id"
   set_or_ask "PUB_USER_EMAIL" "$3" "%sp Git %var" "$PUB_USER_EMAIL" "assert_email"
 
-  initialize_publication_repository
-  ensure_valid_location :initialized
+  initialize_publication_git_repository
+  ensure_valid_location_for_git_publication :initialized
 
   _log_i 1 "bundle publication repository initialized"
 }
 
-initialize_publication_repository() {
-  cd bundle >/dev/null || FATAL "internal error"
+initialize_publication_git_repository() {
+  cd bundle > /dev/null || FATAL "internal error"
 
   # Base git init, if required
   [ ! -f .git ] && {
@@ -349,7 +352,7 @@ initialize_publication_repository() {
   }
 
   # Set origin, if required
-  ORIG="$(git remote get-url origin 2>/dev/null)"
+  ORIG="$(git remote get-url origin 2> /dev/null)"
   [ -n "$ORIG" ] && {
     ask "An origin is already present ($ORIG) do you want ot overwrite it?" || EXIT_UE "User abort"
     git remote remove origin
@@ -360,11 +363,11 @@ initialize_publication_repository() {
   git config user.name "$PUB_USER_NAME"
   git config user.email "$PUB_USER_EMAIL"
 
-  cd - >/dev/null || FATAL "internal error"
+  cd - > /dev/null || FATAL "internal error"
 
   # Project: gitignore
   grep -sq "^bundle/$" .gitignore || {
-    echo -e "\n####\nbundle/" >>.gitignore
+    echo -e "\n####\nbundle/" >> .gitignore
     _log_d 1 "bundle project .gitignore updated"
   }
 }
@@ -376,15 +379,15 @@ require_ent_project_dir() {
     && FATAL "The current dir (\"$PWD\") doesn't seem to be a valid bundle project (not bundle dir)"
 }
 
-ensure_valid_location() {
+ensure_valid_location_for_git_publication() {
   # valid path
-  [ ! -f ".ent-prj" ] && {
-    [ -f "./bundle/$C_BUNDLE_DESCRIPTOR_FILE_NAME" ] && {
+  if [ ! -f "$C_ENT_PRJ_FILE" ]; then
+    if [ -f "./bundle/$C_BUNDLE_DESCRIPTOR_FILE_NAME" ]; then
       generate_ent_project_file
-    }
-  }
-
-  [ ! -f ".ent-prj" ] && FATAL "The current dir (\"$PWD\") doesn't seem to be a valid bundle project"
+    else
+      FATAL "The current dir (\"$PWD\") doesn't seem to be a valid bundle project"
+    fi
+  fi
 
   if [ "$1" = ":initialized" ]; then
     cd bundle || FATAL "internal error"
@@ -392,12 +395,12 @@ ensure_valid_location() {
     # git initialized
     [ -d ".git" ] || FATAL "Publication repository is not initialized"
 
-    ORIG=$(git remote get-url origin 2>/dev/null)
+    ORIG=$(git remote get-url origin 2> /dev/null)
     [ -z "$ORIG" ] && FATAL "Repo not initialized (run \"${0##*/} init ...\")"
 
     # git user data set
-    [ -z "$(git config user.name 2>/dev/null)" ] && FATAL 'Publication user name is not set'
-    [ -z "$(git config user.email 2>/dev/null)" ] && FATAL 'Publication user email is not set'
+    [ -z "$(git config user.name 2> /dev/null)" ] && FATAL 'Publication user name is not set'
+    [ -z "$(git config user.email 2> /dev/null)" ] && FATAL 'Publication user email is not set'
 
     # git master branch
     if [ "$(git ls-remote origin master)" ]; then
@@ -407,54 +410,44 @@ ensure_valid_location() {
       if [ "$(git status --porcelain)" ]; then
         local BBN="__AUTOSAVE_$(date -u '+%Y-%m-%dT%H-%M-%S%z')__"
         _log_w 1 "Saving the local changes to the backup branch: \"$BBN\""
-        git reset HEAD 2>/dev/null
-        git checkout -b "$BBN" &&
-          git add -A &&
-          git commit -m "$BBN"
+        git reset HEAD 2> /dev/null
+        git checkout -b "$BBN" \
+          && git add -A \
+          && git commit -m "$BBN"
       fi
 
       _log_d 1 "Checking out the remote master"
       git fetch origin master
       git checkout -b master origin/master
     else
-      echo "" >.gitignore
+      echo "" > .gitignore
       git add -A
       git commit -m "init"
       git checkout -b master
       git push --set-upstream origin master
     fi
 
-    cd - >/dev/null || FATAL "internal error"
+    cd - > /dev/null || FATAL "internal error"
   fi
 
   return 0
 }
 
 # If some information is missing tries to read it from the project
-read_missing_pub_info_from_project() {
+read_missing_pub_info_from_project_sources_git() {
   cd .. || FATAL "internal error"
 
   [ -z "$PUB_USER_NAME" ] && {
-    PUB_USER_NAME="$(git config user.name 2>/dev/null)"
+    PUB_USER_NAME="$(git config user.name 2> /dev/null)"
     [ -n "$PUB_USER_NAME" ] && _log_d 1 "Assuming user name \"$PUB_USER_NAME\" from the bundle project dir"
   }
 
   [ -z "$PUB_USER_EMAIL" ] && {
-    PUB_USER_EMAIL="$(git config user.email 2>/dev/null)"
+    PUB_USER_EMAIL="$(git config user.email 2> /dev/null)"
     [ -n "$PUB_USER_EMAIL" ] && _log_d 1 "Assuming user email \"$PUB_USER_EMAIL\" from the bundle parent project dir"
   }
 
-  cd - >/dev/null || FATAL "internal error"
-}
-
-assert_db_type() {
-  case "$2" in
-  mysql | postgresql) return 0 ;;
-  *)
-    _log_e 0 "Value of $1 ($2) is not a valid production database type"
-    return 1
-    ;;
-  esac
+  cd - > /dev/null || FATAL "internal error"
 }
 
 # ######################################################################################################################
@@ -462,14 +455,14 @@ assert_db_type() {
 # ######################################################################################################################
 H() {
   case $1 in
-  short)
-    echo -e "Helps managing Entando bundle projects | Syntax: (run ${0##*/} [-i|-m] <sub-command>)"
-    ;;
-  *)
-    echo -e "Helps managing Entando bundle projects | Syntax: (run ${0##*/} [-i|-m] <sub-command>)"
-    echo "sub-commands:"
-    grep '#''H:' "$0" | sed 's/[[:space:]]*\(.*\))[[:space:]]*#''H:\(.*\)/  - \1: \2/'
-    ;;
+    short)
+      echo -e "Helps managing Entando bundle projects | Syntax: (run ${0##*/} [-i|-m] <sub-command>)"
+      ;;
+    *)
+      echo -e "Helps managing Entando bundle projects | Syntax: (run ${0##*/} [-i|-m] <sub-command>)"
+      echo "sub-commands:"
+      grep '#''H:' "$0" | sed 's/[[:space:]]*\(.*\))[[:space:]]*#''H:\(.*\)/  - \1: \2/'
+      ;;
   esac
 }
 
@@ -478,6 +471,6 @@ if [ "$1" = "-h" ] || [ "$1" == "" ]; then
 fi
 
 . s/_base.sh
-cd - >/dev/null || FATAL "internal error"
+cd - > /dev/null || FATAL "internal error"
 
 RUN "$@"
