pre2

diff --git a/auto-install b/auto-install
--- a/auto-install
+++ b/auto-install
@@ -45,7 +45,7 @@ ent_clone_repo_DC7C420E09B4492D() {
     return 0
   fi
 
-  if [[ ! -d "$FLD" || "$UPDATE" -ne 0 ]]; then
+  if [[ ! -f "$FLD/.git" || "$UPDATE" -ne 0 ]]; then
     (
       if [ "$TAG" = "master" ]; then
         echo "Please specify a release tag or a release branch" 1>&2
@@ -74,6 +74,10 @@ ent_clone_repo_DC7C420E09B4492D() {
           echo "> Unable to checkout the given tag or branch of $DSC \"$TAG\"" 1>&2
           exit 92
         fi
+        
+        echo "> Checked out tag/branch \"$TAG\" of repository $DSC: " 1>&2
+        echo "> Status: "
+        git log --pretty=format:'%H|%ci' | head -n 1 | sed -E 's/\|/\n/g'
       fi
       if [ $? ]; then
         cd - > /dev/null
@@ -117,6 +121,8 @@ ENT_RUNNER_DC7C420E09B4492D() {
 
   # ----------------------------------------------------------------------------------------------------
   # OPTIONS
+  # ----------------------------------------------------------------------------------------------------
+
   for opt in "$@"; do
     case "$opt" in
       --sourced)
@@ -180,48 +186,65 @@ ENT_RUNNER_DC7C420E09B4492D() {
 
   # ----------------------------------------------------------------------------------------------------
   # DOWNLOAD
+  # ----------------------------------------------------------------------------------------------------
+
   $CURR_DIR || cd "$HOME"
 
   local TGT_DIR="$PWD"
   local ENTANDO_DIR='.entando'
   local ENT_DIR="ent"
 
+  # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+  # RELEASE INSTALLATION
+  
+  echo "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
+  echo "> Downloading the ENTANDO RELEASE $ENTANDO_RELEASE"
+  echo "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
+  
   (
     git --version
     [ $? -ne 0 ] && echo "please install git" 1>&2 && exit 91
 
     set -e
 
-    # RELEASE
-    echo "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
-    echo "> Downloading the ENTANDO RELEASE $ENTANDO_RELEASE"
-    echo "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
-
-    mkdir -p "$ENTANDO_DIR/$ENT_DIR"
-    cd "$ENTANDO_DIR/$ENT_DIR"
+    mkdir -p "$ENTANDO_DIR/$ENT_DIR/rel"
+    cd "$ENTANDO_DIR/$ENT_DIR/rel"
 
     ent_clone_repo_DC7C420E09B4492D "$ENTANDO_RELEASES_REPO_URL" \
-      "$ENTANDO_RELEASE" "$ENTANDO_RELEASE" "release" $UPDATE_REL || exit "$?"
+      "$ENTANDO_RELEASE" "$ENTANDO_RELEASE" "release" "$UPDATE_REL" || exit "$?"
+
   ) || return "$?"
 
-  cd "$ENTANDO_DIR/$ENT_DIR"
-  # shellcheck disable=SC1090
-  [[ -z "${ENTANDO_CLI_VERSION:-}" ]] && source "./$ENTANDO_RELEASE/dist/manifest"
-  [[ -z "${ENTANDO_CLI_VERSION:-}" ]] && echo "Unable to determine the proper entando cli version" 1>&2 && exit 1
+  # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+  # ASSUMING THE RELEASE PARAMETERS
+  
+  # Automatic selection of the CLI version, is not explicitly provided
+  if [ -z "${ENTANDO_CLI_VERSION:-}" ]; then
+      ENTANDO_CLI_VERSION="$(
+      # shellcheck disable=SC1090
+      source "$ENTANDO_DIR/$ENT_DIR/rel/$ENTANDO_RELEASE/manifest" &>/dev/null
+      echo "$ENTANDO_CLI_VERSION"
+    )"
+  fi
 
+  # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+  # CLI
+  
+  echo "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
+  echo "> Downloading the ENTANDO CLI ${ENTANDO_CLI_VERSION:-???}"
+  echo "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
+    
   (
-    # CLI
-    echo "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
-    echo "> Downloading the ENTANDO CLI $ENTANDO_CLI_VERSION"
-    echo "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
-    cd "$ENTANDO_RELEASE"
-    mkdir -p "./cli"
-    ent_clone_repo_DC7C420E09B4492D "https://github.com/entando/entando-cli" \
-      "$ENTANDO_CLI_VERSION" "cli/$ENTANDO_CLI_VERSION" "version" $UPDATE_CLI || exit "$?"
+    # shellcheck disable=SC2030
+    [[ -z "${ENTANDO_CLI_VERSION:-}" ]] && echo "Unable to determine the proper entando cli version" 1>&2 && exit 1
+    
+    mkdir -p "$ENTANDO_DIR/$ENT_DIR/cli/w"
+    cd "$ENTANDO_DIR/$ENT_DIR/cli"
 
-    cd "cli/$ENTANDO_CLI_VERSION"
-    rm -rf ./dist
-    ln -sf "../../dist" ./
+    ent_clone_repo_DC7C420E09B4492D "https://github.com/entando/entando-cli" \
+      "$ENTANDO_CLI_VERSION" "$ENTANDO_CLI_VERSION" "version" $UPDATE_CLI || exit "$?"
+
+    echo "DEFAULT_ENTANDO_RELEASE=$ENTANDO_RELEASE" > "$ENTANDO_CLI_VERSION/w/.first-run-cfg"
   ) || return "$?"
 
   # ----------------------------------------------------------------------------------------------------
@@ -233,7 +256,7 @@ ENT_RUNNER_DC7C420E09B4492D() {
   # Shortcuts generation
   local ENTANDO_HOME="$TGT_DIR/$ENTANDO_DIR"
   local ENTS_ROOT="$ENTANDO_HOME/$ENT_DIR"
-  local ENT_HOME="$ENTS_ROOT/$ENTANDO_RELEASE/cli/$ENTANDO_CLI_VERSION"
+  local ENT_HOME="$ENTS_ROOT/cli/$ENTANDO_CLI_VERSION"
   for script_name in "activate" "activate-PLACEHOLDER_RELEASE" "deactivate"; do
     local script_file="$ENTANDO_HOME/${script_name/PLACEHOLDER_RELEASE/$ENTANDO_RELEASE}"
     chmod u=rwx "$script_file" 2>/dev/null || true
diff --git a/bin/mod/ent-quickstart b/bin/mod/ent-quickstart
--- a/bin/mod/ent-quickstart
+++ b/bin/mod/ent-quickstart
@@ -159,6 +159,25 @@ if [ "$ENTANDO_RELEASE" != "$C_QUICKSTART_DEFAULT_RELEASE" ]; then
   assert_ver "ENTANDO_RELEASE" "$ENTANDO_RELEASE" || FATAL "Please provide a valid release tag"
 fi
 
+#-----------------------------------------------------------------------------------------------------------------------
+# CLONES THE RELEASE TO INSTALL, IF REQUIRED
+(
+  cd "$ENTANDO_ENT_HOME/../../rel" || FATAL "Unable to enter the release base directory"
+  if [ ! -d "$ENTANDO_RELEASE" ]; then
+    _log_i 0 "Entando release $ENTANDO_RELEASE not present, downloading.."
+    git_clone_repo "$ENTANDO_RELEASES_REPO_URL" "$ENTANDO_RELEASE" "$ENTANDO_RELEASE" "RELEASE $DESC"
+  else
+    _log_i 0 "Entando release $ENTANDO_RELEASE already present"
+  fi
+  
+  cd "$ENTANDO_RELEASE" || FATAL "Unable to enter the release directory"
+) || exit "$?"
+
+ENTANDO_RELEASE_DIR="$(cd "$ENTANDO_ENT_HOME/../../rel/$ENTANDO_RELEASE" && pwd)"
+[ -d "$ENTANDO_RELEASE_DIR" ] || FATAL "Unable to enter the release directory"
+
+#-----------------------------------------------------------------------------------------------------------------------
+
 # determines the structure and conventions of the entando-releases repository 
 if check_ver "$ENTANDO_RELEASE" "6.3.>=2" "" "string" ||
    check_ver "$ENTANDO_RELEASE" "6.>3.*" "" "string" ||
@@ -518,8 +537,8 @@ RUN_DIRECT() {
   else
     determine_versioned_filename_6_3_0 MANIFEST_TEMPLATE_FILE "${DEPL_SPEC_YAML_FILE}.tpl" "$K8S_TEMPLATE"
   fi
-pwd
-  if [ -f "dist/$MANIFEST_TEMPLATE_FILE" ]; then
+
+  if [ -f "$ENTANDO_RELEASE_DIR/dist/$MANIFEST_TEMPLATE_FILE" ]; then
     _log_i 1 "> Selecting manifest template file \"dist/$MANIFEST_TEMPLATE_FILE\""
   else
     FATAL "Unable to find manifest template file \"dist/$MANIFEST_TEMPLATE_FILE\""
@@ -528,7 +547,7 @@ pwd
   _log_i 2 "> Generating the kubernetes specification file \"w/$DEPL_SPEC_YAML_FILE\" for the deployment"
 
   # shellcheck disable=SC2002
-  cat "dist/$MANIFEST_TEMPLATE_FILE" |
+  cat "$ENTANDO_RELEASE_DIR/dist/$MANIFEST_TEMPLATE_FILE" |
     _perl_sed "s/PLACEHOLDER_ENTANDO_NAMESPACE/$ENTANDO_NAMESPACE/" |
     _perl_sed "s/PLACEHOLDER_ENTANDO_APPNAME/$ENTANDO_APPNAME/" |
     _perl_sed "s/PLACEHOLDER_ENTANDO_SINGLE_HOSTNAME/$SINGLE_HOSTNAME/" |
@@ -550,7 +569,7 @@ pwd
         determine_versioned_filename_6_3_0 CLUSTER_RESOURCES "crd" "$K8S_TEMPLATE"
       fi
       
-      ent-kubectl apply -f "dist/$CLUSTER_RESOURCES"
+      ent-kubectl apply -f "$ENTANDO_RELEASE_DIR/dist/$CLUSTER_RESOURCES"
     }
   }
 
